name: upload

on: [push]

jobs:
  upload:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'build'
          destination: ${{ secrets.GCP_BUCKET }}
